// Generated by IB v1.0.1 gem. Do not edit it manually
// Run `rake ib:open` to refresh

#import <WatchKit/WatchKit.h>
#import <UIKit/UIKit.h>
#import <Foundation/Foundation.h>
#import <CoreGraphics/CoreGraphics.h>
#import <CoreFoundation/CoreFoundation.h>
#import <MapKit/MapKit.h>
#import <ClockKit/ClockKit.h>
#import <SpriteKit/SpriteKit.h>

@interface ComplicationController: NSObject
@end

@interface ExtensionDelegate: NSObject
-(IBAction) applicationDidFinishLaunching;
-(IBAction) applicationDidBecomeActive;
-(IBAction) applicationWillResignActive;

@end

@interface GlanceController: WKInterfaceController
-(IBAction) awakeWithContext:(id) context;
-(IBAction) willActivate;
-(IBAction) didDeactivate;

@end

@interface InterfaceController: WKInterfaceController
-(IBAction) handleTapGesture:(id) sender;
-(IBAction) awakeWithContext:(id) context;
-(IBAction) willActivate;
-(IBAction) didDeactivate;

@end

@interface NotificationController: WKUserNotificationInterfaceController
-(IBAction) init;
-(IBAction) willActivate;
-(IBAction) didDeactivate;

@end

