// Generated by IB v1.0.1 gem. Do not edit it manually
// Run `rake ib:open` to refresh

#import "Stubs.h"

@implementation ComplicationController
@end

@implementation ExtensionDelegate
@end

@implementation GlanceController
@end

@implementation InterfaceController
@end

@implementation NotificationController
@end

